version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: oficinasync-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: oficinasync-storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    ports:
      - "9000:9000" # API do MinIO
      - "9001:9001" # Painel visual do MinIO
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  sqlserver_data:
  minio_data:
